name: patient-service

on:
  push:
    branches: [ main ]
  workflow_dispatch:
env:
  AWS_REGION: ap-south-1
  ACCOUNT_ID: 381492087649
  GITHUB_OIDC_ROLE: arn:aws:iam::381492087649:role/github-actions-deploy-role
  ECR_REPO: bayer-hackathon-registry
  IMAGE_TAG: ${{ github_run_id }}
  LAMBDA_NAME: patient-service-lambda
  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  SONAR_PROJECT_KEY: patient-service
permissions:
  id-token: write
  contents: read
jobs:
  build-scan-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS Credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.GITHUB_OIDC_ROLE }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Git Checkout
      uses: actions/checkout@v4
      with:
        node-version: 20

    - name: Install Dependencies
      run: npm run ci

    - name: Trivy FS Scan
      uses: aquasecurity/trivy-action@0.20.0
      with:
        scan-type: 'fs'
        scan-ref: '.'
        exit-code: '1'
        severity: 'CRITICAL,HIGH'
        format: 'json'
        output: 'trivy-fs-scan.json'

    - name: Sonarqube Scan
      uses: sonarsource/sonarqube-scan-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
          -Dsonar.host.url=${{ env.SONAR_HOST_URL }}
          
    - name: SonarQube Quality Gate
      uses: sonarsource/sonarqube-quality-gate-action@v1
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      timeout-minutes: 10
      
    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2
      
    - name: Build Docker image
      run: |
        docker build -t $ECR_REPO:$IMAGE_TAG .

    - name: Trivy Image Scan
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: ${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}
        exit-code: '1'
        severity: 'CRITICAL,HIGH'
        format: json
        output: trivy-image-scan.json
        
    - name: Install Dockle
      run: |
        curl -sSfL https://github.com/goodwithtech/dockle/releases/latest/download/dockle_Linux_x86_64.tar.gz \
        | tar -xz
        sudo mv dockle /usr/local/bin/
        
    - name: Dockle Scan
      run: |
        dockle --exit-code 1 $ECR_REPO:$IMAGE_TAG

    - name: Tag & Push to ECR
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
        ECR_URI="${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}"
        docker tag ${ECR_REPO}:${IMAGE_TAG} ${ECR_URI}
        docker push ${ECR_URI}
        echo "IMAGE_URI=${ECR_URI}" >> $GITHUB_ENV
    - name: Update Lambda to use new image
      run: |
        aws lambda update-function-code \
          --function-name $LAMBDA_NAME \
          --image-uri $IMAGE_URI
